/*
 * Copyright (C) 2016 Dmitry Tsvetkovsky
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ru.dmig.infinityflight.gui;

import javax.swing.JOptionPane;
import ru.dmig.infinityflight.logic.*;

/**
 *
 * @author Dmig
 */
public final class Gui extends javax.swing.JFrame {

    public static Gui gui;

    private static class GuiStarter extends Thread {

        public GuiStarter() {
            this.setName("Guier");
        }

        @Override
        public void run() {
            try {
                ru.epiclib.gui.Util.setStyle();
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(-11);
            }

            gui = new Gui();
            gui.setVisible(true);
        }
    }

    public static void start() {
        GuiStarter starter = new GuiStarter();
        starter.start();
    }

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        update();
    }

    public void update() {
        Ship ship = InfinityFlight.ship;

        foodAmount.setText(ship.storage.getFoodAmount() + "/" + ship.storage.getMaxFoodAmount());
        fuelAmount.setText(ship.storage.getFuelAmount() + "/" + ship.storage.getMaxFuelAmount());
        energyAmount.setText(ship.getEnergyAmount() + "");
        distanceToStation.setText(ship.getDistanceToStation() + "");
        
        //personalAmount.setText(ship.personel.size() + "/" + ship.getMaxPersonalAmount());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoBar = new javax.swing.JPanel();
        foodAmountL = new javax.swing.JLabel();
        foodAmount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fuelAmountL = new javax.swing.JLabel();
        fuelAmount = new javax.swing.JLabel();
        energyAmountL = new javax.swing.JLabel();
        energyAmount = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        distanceToStationL = new javax.swing.JLabel();
        distanceToStation = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        tourismPanel = new javax.swing.JPanel();
        tFirstL = new javax.swing.JLabel();
        tFirst = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tSecondL = new javax.swing.JLabel();
        tSecond = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        tThirdL = new javax.swing.JLabel();
        tThird = new javax.swing.JLabel();
        personalAmountL = new javax.swing.JLabel();
        personalAmount = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        gameSubsMenus = new javax.swing.JMenu();
        settingsMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();
        personalMenu = new javax.swing.JMenu();
        touristMenu = new javax.swing.JMenu();
        roomMenu = new javax.swing.JMenu();
        enginesMenu = new javax.swing.JMenu();
        reactorMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N

        foodAmountL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        foodAmountL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodAmountL.setText("Food amount");

        foodAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        foodAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodAmount.setText("5000/10000");
        foodAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fuelAmountL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        fuelAmountL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelAmountL.setText("Fuel amount");

        fuelAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        fuelAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelAmount.setText("400/500");
        fuelAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        energyAmountL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        energyAmountL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energyAmountL.setText("Energy");

        energyAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        energyAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energyAmount.setText("0");
        energyAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        distanceToStationL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        distanceToStationL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceToStationL.setText("Distance to Station");

        distanceToStation.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        distanceToStation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceToStation.setText("85");
        distanceToStation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout InfoBarLayout = new javax.swing.GroupLayout(InfoBar);
        InfoBar.setLayout(InfoBarLayout);
        InfoBarLayout.setHorizontalGroup(
            InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoBarLayout.createSequentialGroup()
                .addGroup(InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(energyAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(energyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(distanceToStationL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(distanceToStation, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        InfoBarLayout.setVerticalGroup(
            InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoBarLayout.createSequentialGroup()
                .addComponent(foodAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(InfoBarLayout.createSequentialGroup()
                .addComponent(fuelAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(InfoBarLayout.createSequentialGroup()
                .addComponent(energyAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(InfoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoBarLayout.createSequentialGroup()
                    .addComponent(distanceToStationL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(distanceToStation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tFirstL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tFirstL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tFirstL.setText("First");

        tFirst.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tFirst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tFirst.setText("0/0");
        tFirst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tSecondL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tSecondL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tSecondL.setText("Second");
        tSecondL.setPreferredSize(new java.awt.Dimension(54, 17));

        tSecond.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tSecond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tSecond.setText("0/0");
        tSecond.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tThirdL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tThirdL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tThirdL.setText("Third");
        tThirdL.setPreferredSize(new java.awt.Dimension(54, 17));

        tThird.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        tThird.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tThird.setText("0/0");
        tThird.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tourismPanelLayout = new javax.swing.GroupLayout(tourismPanel);
        tourismPanel.setLayout(tourismPanelLayout);
        tourismPanelLayout.setHorizontalGroup(
            tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tourismPanelLayout.createSequentialGroup()
                .addGroup(tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tFirstL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tSecondL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tThird, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tThirdL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        tourismPanelLayout.setVerticalGroup(
            tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator5)
            .addGroup(tourismPanelLayout.createSequentialGroup()
                .addGroup(tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tourismPanelLayout.createSequentialGroup()
                        .addComponent(tFirstL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tourismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator6)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tourismPanelLayout.createSequentialGroup()
                            .addComponent(tSecondL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tourismPanelLayout.createSequentialGroup()
                        .addComponent(tThirdL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tThird, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        personalAmountL.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        personalAmountL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalAmountL.setText("Personal");

        personalAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        personalAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personalAmount.setText("7/10");
        personalAmount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        gameSubsMenus.setText("Game");

        settingsMenu.setText("Settings");
        settingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsMenuActionPerformed(evt);
            }
        });
        gameSubsMenus.add(settingsMenu);

        helpMenu.setText("Help");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });
        gameSubsMenus.add(helpMenu);

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        gameSubsMenus.add(aboutMenu);

        jMenuBar1.add(gameSubsMenus);

        personalMenu.setText("Personal");
        personalMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(personalMenu);

        touristMenu.setText("Tourists");
        touristMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touristMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(touristMenu);

        roomMenu.setText("Rooms");
        roomMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(roomMenu);

        enginesMenu.setText("Engines");
        enginesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enginesMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(enginesMenu);

        reactorMenu.setText("Reactors");
        reactorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reactorMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(reactorMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tourismPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personalAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tourismPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(personalAmountL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(personalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personalMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalMenuActionPerformed

    private void touristMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touristMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_touristMenuActionPerformed

    private void roomMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomMenuActionPerformed

    private void enginesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enginesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enginesMenuActionPerformed

    private void reactorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reactorMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reactorMenuActionPerformed

    private void settingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsMenuActionPerformed

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMenuActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoBar;
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JLabel distanceToStation;
    private javax.swing.JLabel distanceToStationL;
    private javax.swing.JLabel energyAmount;
    private javax.swing.JLabel energyAmountL;
    private javax.swing.JMenu enginesMenu;
    private javax.swing.JLabel foodAmount;
    private javax.swing.JLabel foodAmountL;
    private javax.swing.JLabel fuelAmount;
    private javax.swing.JLabel fuelAmountL;
    private javax.swing.JMenu gameSubsMenus;
    private javax.swing.JMenuItem helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel personalAmount;
    private javax.swing.JLabel personalAmountL;
    private javax.swing.JMenu personalMenu;
    private javax.swing.JMenu reactorMenu;
    private javax.swing.JMenu roomMenu;
    private javax.swing.JMenuItem settingsMenu;
    private javax.swing.JLabel tFirst;
    private javax.swing.JLabel tFirstL;
    private javax.swing.JLabel tSecond;
    private javax.swing.JLabel tSecondL;
    private javax.swing.JLabel tThird;
    private javax.swing.JLabel tThirdL;
    private javax.swing.JPanel tourismPanel;
    private javax.swing.JMenu touristMenu;
    // End of variables declaration//GEN-END:variables
}
