/*
 * Copyright (C) 2016 Dmitry Tsvetkovsky
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ru.dmig.infinityflight.gui;

import javax.swing.JOptionPane;
import ru.dmig.infinityflight.logic.*;

/**
 *
 * @author Dmig
 */
public final class StationGui extends javax.swing.JFrame {

    public static StationGui stationGui;

    private static class GuiStarter extends Thread {

        public GuiStarter() {
            this.setName("StationGui");
        }

        @Override
        public void run() {
            try {
                ru.epiclib.gui.Util.setStyle();
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(-11);
            }

            StationGui gui = new StationGui();
            gui.setVisible(true);
        }
    }

    public static void start() {
        GuiStarter starter = new GuiStarter();
        starter.start();
    }

    public StationGui() {
        initComponents();
        update(true);
    }

    public void update(boolean all) {

        Station station = InfinityFlight.ship.station;

        if (all) {
            stationLabel.setText(station.getName() + " - " + station.getSizeString() + " station");
        }

        //Sliders
        if (all) {
            thirdClassSlider.setMaximum(station.getTouristsAmount()[0]);
            secondClassSlider.setMaximum(station.getTouristsAmount()[1]);
            firstClassSlider.setMaximum(station.getTouristsAmount()[2]);

            workerSlider.setMaximum(station.getWorkersAmount()[0]);
            engineerSlider.setMaximum(station.getWorkersAmount()[1]);
            medicSlider.setMaximum(station.getWorkersAmount()[2]);
            guardSlider.setMaximum(station.getWorkersAmount()[3]);
            biologistSlider.setMaximum(station.getWorkersAmount()[4]);

            fuelSlider.setMaximum(Math.round(station.storage.getFuelAmount()));
            foodSlider.setMaximum(station.storage.getFoodAmount());
            medicineSlider.setMaximum(station.storage.getMedicineAmount());
            spareSlider.setMaximum(station.storage.getSpareAmount());
        }

        thirdClassAmount.setText(thirdClassSlider.getValue() + "/" + thirdClassSlider.getMaximum());
        secondClassAmount.setText(secondClassSlider.getValue() + "/" + secondClassSlider.getMaximum());
        firstClassAmount.setText(firstClassSlider.getValue() + "/" + firstClassSlider.getMaximum());

        workerAmount.setText(workerSlider.getValue() + "/" + workerSlider.getMaximum());
        engineerAmount.setText(engineerSlider.getValue() + "/" + engineerSlider.getMaximum());
        medicAmount.setText(medicSlider.getValue() + "/" + medicSlider.getMaximum());
        guardAmount.setText(guardSlider.getValue() + "/" + guardSlider.getMaximum());
        biologistAmount.setText(biologistSlider.getValue() + "/" + biologistSlider.getMaximum());

        fuelAmount.setText(fuelSlider.getValue() + "/" + fuelSlider.getMaximum());
        foodAmount.setText(foodSlider.getValue() + "/" + foodSlider.getMaximum());
        medicineAmount.setText(medicineSlider.getValue() + "/" + medicineSlider.getMaximum());
        sparesAmount.setText(spareSlider.getValue() + "/" + spareSlider.getMaximum());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationLabel = new javax.swing.JLabel();
        thirdClass = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        thirdClassSlider = new javax.swing.JSlider();
        thirdClassAmount = new javax.swing.JLabel();
        secondClass = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        secondClassSlider = new javax.swing.JSlider();
        secondClassAmount = new javax.swing.JLabel();
        firstClass = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        firstClassSlider = new javax.swing.JSlider();
        firstClassAmount = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        res = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        workerPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        workerSlider = new javax.swing.JSlider();
        workerAmount = new javax.swing.JLabel();
        engineerPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        engineerSlider = new javax.swing.JSlider();
        engineerAmount = new javax.swing.JLabel();
        medicPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        medicSlider = new javax.swing.JSlider();
        medicAmount = new javax.swing.JLabel();
        guardPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        guardSlider = new javax.swing.JSlider();
        guardAmount = new javax.swing.JLabel();
        biologistPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        biologistSlider = new javax.swing.JSlider();
        biologistAmount = new javax.swing.JLabel();
        fuelPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fuelSlider = new javax.swing.JSlider();
        fuelAmount = new javax.swing.JLabel();
        foodPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        foodSlider = new javax.swing.JSlider();
        foodAmount = new javax.swing.JLabel();
        medicinePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        medicineSlider = new javax.swing.JSlider();
        medicineAmount = new javax.swing.JLabel();
        sparesPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        spareSlider = new javax.swing.JSlider();
        sparesAmount = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        button = new javax.swing.JButton();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 750));
        setPreferredSize(new java.awt.Dimension(500, 750));

        stationLabel.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        stationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationLabel.setText("Oreon - big station");

        thirdClass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Third class");
        jLabel1.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel1.setPreferredSize(new java.awt.Dimension(91, 17));

        thirdClassSlider.setPaintLabels(true);
        thirdClassSlider.setPaintTicks(true);
        thirdClassSlider.setValue(0);
        thirdClassSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        thirdClassSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        thirdClassSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        thirdClassSlider.setValueIsAdjusting(true);

        thirdClassAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        thirdClassAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thirdClassAmount.setText("NaN");
        thirdClassAmount.setToolTipText("Price: NaN");
        thirdClassAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        thirdClassAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        thirdClassAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout thirdClassLayout = new javax.swing.GroupLayout(thirdClass);
        thirdClass.setLayout(thirdClassLayout);
        thirdClassLayout.setHorizontalGroup(
            thirdClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thirdClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thirdClassAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        thirdClassLayout.setVerticalGroup(
            thirdClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thirdClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thirdClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thirdClassAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        secondClass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Second class");

        secondClassSlider.setPaintLabels(true);
        secondClassSlider.setPaintTicks(true);
        secondClassSlider.setValue(0);
        secondClassSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        secondClassSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        secondClassSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        secondClassSlider.setValueIsAdjusting(true);

        secondClassAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        secondClassAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondClassAmount.setText("NaN");
        secondClassAmount.setToolTipText("Price: NaN");
        secondClassAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        secondClassAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        secondClassAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout secondClassLayout = new javax.swing.GroupLayout(secondClass);
        secondClass.setLayout(secondClassLayout);
        secondClassLayout.setHorizontalGroup(
            secondClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(secondClassAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        secondClassLayout.setVerticalGroup(
            secondClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondClassAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        firstClass.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("First class");
        jLabel5.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(91, 17));

        firstClassSlider.setPaintLabels(true);
        firstClassSlider.setPaintTicks(true);
        firstClassSlider.setValue(0);
        firstClassSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        firstClassSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        firstClassSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        firstClassSlider.setValueIsAdjusting(true);

        firstClassAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        firstClassAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstClassAmount.setText("NaN");
        firstClassAmount.setToolTipText("Price: NaN");
        firstClassAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        firstClassAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        firstClassAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout firstClassLayout = new javax.swing.GroupLayout(firstClass);
        firstClass.setLayout(firstClassLayout);
        firstClassLayout.setHorizontalGroup(
            firstClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstClassLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstClassAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        firstClassLayout.setVerticalGroup(
            firstClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstClassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstClassSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstClassAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        res.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Workers");
        jLabel7.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(91, 17));

        workerSlider.setPaintLabels(true);
        workerSlider.setPaintTicks(true);
        workerSlider.setValue(0);
        workerSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        workerSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        workerSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        workerSlider.setValueIsAdjusting(true);

        workerAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        workerAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        workerAmount.setText("NaN");
        workerAmount.setToolTipText("Price: NaN");
        workerAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        workerAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        workerAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout workerPanelLayout = new javax.swing.GroupLayout(workerPanel);
        workerPanel.setLayout(workerPanelLayout);
        workerPanelLayout.setHorizontalGroup(
            workerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workerSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        workerPanelLayout.setVerticalGroup(
            workerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workerSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workerAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Worker", workerPanel);

        jLabel17.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Engineers");
        jLabel17.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel17.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel17.setPreferredSize(new java.awt.Dimension(91, 17));

        engineerSlider.setPaintLabels(true);
        engineerSlider.setPaintTicks(true);
        engineerSlider.setValue(0);
        engineerSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        engineerSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        engineerSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        engineerSlider.setValueIsAdjusting(true);

        engineerAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        engineerAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        engineerAmount.setText("NaN");
        engineerAmount.setToolTipText("Price: NaN");
        engineerAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        engineerAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        engineerAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout engineerPanelLayout = new javax.swing.GroupLayout(engineerPanel);
        engineerPanel.setLayout(engineerPanelLayout);
        engineerPanelLayout.setHorizontalGroup(
            engineerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(engineerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(engineerSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(engineerAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        engineerPanelLayout.setVerticalGroup(
            engineerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(engineerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(engineerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(engineerSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(engineerAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Engineer", engineerPanel);

        jLabel19.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Medics");
        jLabel19.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel19.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel19.setPreferredSize(new java.awt.Dimension(91, 17));

        medicSlider.setPaintLabels(true);
        medicSlider.setPaintTicks(true);
        medicSlider.setValue(0);
        medicSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        medicSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        medicSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        medicSlider.setValueIsAdjusting(true);

        medicAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        medicAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicAmount.setText("NaN");
        medicAmount.setToolTipText("Price: NaN");
        medicAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        medicAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        medicAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout medicPanelLayout = new javax.swing.GroupLayout(medicPanel);
        medicPanel.setLayout(medicPanelLayout);
        medicPanelLayout.setHorizontalGroup(
            medicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        medicPanelLayout.setVerticalGroup(
            medicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medicSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medic", medicPanel);

        jLabel21.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Guards");
        jLabel21.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel21.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel21.setPreferredSize(new java.awt.Dimension(91, 17));

        guardSlider.setPaintLabels(true);
        guardSlider.setPaintTicks(true);
        guardSlider.setValue(0);
        guardSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        guardSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        guardSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        guardSlider.setValueIsAdjusting(true);

        guardAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        guardAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        guardAmount.setText("NaN");
        guardAmount.setToolTipText("Price: NaN");
        guardAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        guardAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        guardAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout guardPanelLayout = new javax.swing.GroupLayout(guardPanel);
        guardPanel.setLayout(guardPanelLayout);
        guardPanelLayout.setHorizontalGroup(
            guardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        guardPanelLayout.setVerticalGroup(
            guardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Guard", guardPanel);

        jLabel23.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Biologists");
        jLabel23.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel23.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel23.setPreferredSize(new java.awt.Dimension(91, 17));

        biologistSlider.setPaintLabels(true);
        biologistSlider.setPaintTicks(true);
        biologistSlider.setValue(0);
        biologistSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        biologistSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        biologistSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        biologistSlider.setValueIsAdjusting(true);

        biologistAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        biologistAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        biologistAmount.setText("NaN");
        biologistAmount.setToolTipText("Price: NaN");
        biologistAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        biologistAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        biologistAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout biologistPanelLayout = new javax.swing.GroupLayout(biologistPanel);
        biologistPanel.setLayout(biologistPanelLayout);
        biologistPanelLayout.setHorizontalGroup(
            biologistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biologistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(biologistSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(biologistAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        biologistPanelLayout.setVerticalGroup(
            biologistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biologistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biologistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biologistSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biologistAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Biologist", biologistPanel);

        javax.swing.GroupLayout resLayout = new javax.swing.GroupLayout(res);
        res.setLayout(resLayout);
        resLayout.setHorizontalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        resLayout.setVerticalGroup(
            resLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("res");

        fuelPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fuel");
        jLabel9.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(91, 17));

        fuelSlider.setPaintLabels(true);
        fuelSlider.setPaintTicks(true);
        fuelSlider.setValue(0);
        fuelSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        fuelSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        fuelSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        fuelSlider.setValueIsAdjusting(true);

        fuelAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        fuelAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fuelAmount.setText("NaN");
        fuelAmount.setToolTipText("Price: NaN");
        fuelAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        fuelAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        fuelAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout fuelPanelLayout = new javax.swing.GroupLayout(fuelPanel);
        fuelPanel.setLayout(fuelPanelLayout);
        fuelPanelLayout.setHorizontalGroup(
            fuelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fuelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        fuelPanelLayout.setVerticalGroup(
            fuelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fuelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fuelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fuelSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fuelAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        foodPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Food");
        jLabel11.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(91, 17));

        foodSlider.setPaintLabels(true);
        foodSlider.setPaintTicks(true);
        foodSlider.setValue(0);
        foodSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        foodSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        foodSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        foodSlider.setValueIsAdjusting(true);

        foodAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        foodAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodAmount.setText("NaN");
        foodAmount.setToolTipText("Price: NaN");
        foodAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        foodAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        foodAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout foodPanelLayout = new javax.swing.GroupLayout(foodPanel);
        foodPanel.setLayout(foodPanelLayout);
        foodPanelLayout.setHorizontalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foodAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        foodPanelLayout.setVerticalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(foodSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        medicinePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Medicine");
        jLabel13.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel13.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel13.setPreferredSize(new java.awt.Dimension(91, 17));

        medicineSlider.setPaintLabels(true);
        medicineSlider.setPaintTicks(true);
        medicineSlider.setValue(0);
        medicineSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        medicineSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        medicineSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        medicineSlider.setValueIsAdjusting(true);

        medicineAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        medicineAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        medicineAmount.setText("NaN");
        medicineAmount.setToolTipText("Price: NaN");
        medicineAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        medicineAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        medicineAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout medicinePanelLayout = new javax.swing.GroupLayout(medicinePanel);
        medicinePanel.setLayout(medicinePanelLayout);
        medicinePanelLayout.setHorizontalGroup(
            medicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicineSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(medicineAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        medicinePanelLayout.setVerticalGroup(
            medicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(medicinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medicineSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicineAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sparesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Spares");
        jLabel15.setMaximumSize(new java.awt.Dimension(91, 17));
        jLabel15.setMinimumSize(new java.awt.Dimension(91, 17));
        jLabel15.setPreferredSize(new java.awt.Dimension(91, 17));

        spareSlider.setPaintLabels(true);
        spareSlider.setPaintTicks(true);
        spareSlider.setValue(0);
        spareSlider.setMaximumSize(new java.awt.Dimension(32767, 40));
        spareSlider.setMinimumSize(new java.awt.Dimension(213, 40));
        spareSlider.setPreferredSize(new java.awt.Dimension(213, 40));
        spareSlider.setValueIsAdjusting(true);

        sparesAmount.setFont(new java.awt.Font("Gulim", 0, 14)); // NOI18N
        sparesAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sparesAmount.setText("NaN");
        sparesAmount.setToolTipText("Price: NaN");
        sparesAmount.setMaximumSize(new java.awt.Dimension(30002, 40));
        sparesAmount.setMinimumSize(new java.awt.Dimension(102, 40));
        sparesAmount.setPreferredSize(new java.awt.Dimension(102, 40));

        javax.swing.GroupLayout sparesPanelLayout = new javax.swing.GroupLayout(sparesPanel);
        sparesPanel.setLayout(sparesPanelLayout);
        sparesPanelLayout.setHorizontalGroup(
            sparesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sparesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spareSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sparesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sparesPanelLayout.setVerticalGroup(
            sparesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sparesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sparesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spareSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sparesAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        button.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        button.setText("Buy / Hire ");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thirdClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secondClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fuelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foodPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medicinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sparesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(stationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thirdClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foodPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sparesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        
        Ship ship = InfinityFlight.ship;
        Station station = ship.station;
        
        //Tourists
        
        //Workers
        
        Storage storage = ship.storage;
        
        if(fuelSlider.getValue() > 0) {
            storage.setFuelAmount(storage.getFuelAmount() + fuelSlider.getValue());
            station.storage.setFuelAmount(station.storage.getFuelAmount() - fuelSlider.getValue());
        }
        
        if(foodSlider.getValue() > 0) {
            storage.setFoodAmount(storage.getFoodAmount() + foodSlider.getValue());
            station.storage.setFoodAmount(station.storage.getFoodAmount() - foodSlider.getValue());
        }
        
        if(medicineSlider.getValue() > 0) {
            storage.setMedicineAmount((short) (storage.getMedicineAmount() + medicineSlider.getValue()));
            station.storage.setMedicineAmount((short) (station.storage.getMedicineAmount() - medicineSlider.getValue()));
        }
        
        if(spareSlider.getValue() > 0) {
            storage.setSpareAmount((short) (storage.getSpareAmount() + spareSlider.getValue()));
            station.storage.setSpareAmount((short) (station.storage.getSpareAmount() - spareSlider.getValue()));
        }
        
        update(true);
    }//GEN-LAST:event_buttonActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        update(false);
    }//GEN-LAST:event_updateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biologistAmount;
    private javax.swing.JPanel biologistPanel;
    private javax.swing.JSlider biologistSlider;
    private javax.swing.JButton button;
    private javax.swing.JLabel engineerAmount;
    private javax.swing.JPanel engineerPanel;
    private javax.swing.JSlider engineerSlider;
    private javax.swing.JPanel firstClass;
    private javax.swing.JLabel firstClassAmount;
    private javax.swing.JSlider firstClassSlider;
    private javax.swing.JLabel foodAmount;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JSlider foodSlider;
    private javax.swing.JLabel fuelAmount;
    private javax.swing.JPanel fuelPanel;
    private javax.swing.JSlider fuelSlider;
    private javax.swing.JLabel guardAmount;
    private javax.swing.JPanel guardPanel;
    private javax.swing.JSlider guardSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel medicAmount;
    private javax.swing.JPanel medicPanel;
    private javax.swing.JSlider medicSlider;
    private javax.swing.JLabel medicineAmount;
    private javax.swing.JPanel medicinePanel;
    private javax.swing.JSlider medicineSlider;
    private javax.swing.JPanel res;
    private javax.swing.JPanel secondClass;
    private javax.swing.JLabel secondClassAmount;
    private javax.swing.JSlider secondClassSlider;
    private javax.swing.JSlider spareSlider;
    private javax.swing.JLabel sparesAmount;
    private javax.swing.JPanel sparesPanel;
    private javax.swing.JLabel stationLabel;
    private javax.swing.JPanel thirdClass;
    private javax.swing.JLabel thirdClassAmount;
    private javax.swing.JSlider thirdClassSlider;
    private javax.swing.JButton update;
    private javax.swing.JLabel workerAmount;
    private javax.swing.JPanel workerPanel;
    private javax.swing.JSlider workerSlider;
    // End of variables declaration//GEN-END:variables
}
